# =========================
# POSTGRESQL
# =========================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:gastos_user}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/gastos_db}


# =========================
# HIBERNATE
# =========================

quarkus.hibernate-orm.schema-management.strategy=update


# =========================
# CORS
# =========================

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:4200}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization


# =========================
# SMTP - GMAIL
# =========================

quarkus.mailer.host=${MAIL_HOST:smtp.gmail.com}
quarkus.mailer.port=${MAIL_PORT:587}
quarkus.mailer.start-tls=REQUIRED

quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN

quarkus.mailer.username=${MAIL_USERNAME}
quarkus.mailer.password=${MAIL_PASSWORD}
quarkus.mailer.from=${MAIL_FROM}
quarkus.mailer.mock=false


# =========================
# URL PÚBLICA
# =========================

app.public-url=${PUBLIC_APP_URL:http://localhost:4200}


# =========================
# GOOGLE GMAIL API
# =========================

google.gmail.client-id=493496910181-3ts13uhkiptb0kkfg4bii04ooj44hf8f.apps.googleusercontent.com
google.gmail.redirect-uri=https://gastos-perezbuseu.duckdns.org/api/google/oauth/callback