# =========================
# POSTGRESQL
# =========================

quarkus.datasource.db-kind=postgresql

quarkus.datasource.username=${POSTGRES_USER:gastos_user}

quarkus.datasource.password=${POSTGRES_PASSWORD}

quarkus.datasource.jdbc.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/gastos_db}


# =========================
# HIBERNATE
# =========================

quarkus.hibernate-orm.schema-management.strategy=update


# =========================
# CORS
# =========================

quarkus.http.cors.enabled=true

quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:4200}

quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

quarkus.http.cors.headers=Content-Type,Authorization
