# PostgreSQL

quarkus.datasource.db-kind=postgresql

quarkus.datasource.username=gastos_user

quarkus.datasource.password=N7xK9mR2vL8qH4

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gastos_db


# Hibernate

quarkus.hibernate-orm.schema-management.strategy=update


# CORS

quarkus.http.cors.enabled=true

quarkus.http.cors.origins=http://localhost:4200

quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

quarkus.http.cors.headers=Content-Type,Authorization
